namespace SipSavy.Worker.Youtube.Features.ExtractTranscription;

public sealed record ExtractTranscriptionResponse
{
    public string Language { get; set; } = string.Empty;
    public string LanguageCode { get; set; } = string.Empty;
    public bool IsAutoGenerated { get; set; }
    public string Transcription { get; init; } = string.Empty;
};